version: '3.9'
services:
  app:
    image: svenson.ai/webapp-dev
    volumes:
      - /app/node_modules
    ports:
      - 3000:3000
    # command: npx prisma generate
    # command: npx prisma migrate deploy
    command: npx nuxt dev

  postgres:
    ports:
      - 5432:5432
