version: '3.9'
services:
  #  app:
  #    image: svenson.ai/webapp-dev
  #    volumes:
  #      - /app/node_modules
  #    ports:
  #      - 3000:3000
  #    command: npm run dev

  postgres:
    ports:
      - 5432:5432

  redis:
    ports:
      - 6379:6379

  qdrant:
    ports:
      - 6333:6333
