name: ragna_cloud

volumes:
  postgres_data:
  redis_data:
  qdrant_data:
  app_uploads:

services:
  app:
    container_name: app
    restart: unless-stopped
    working_dir: /app
    volumes:
      - app_uploads:/app/uploads:rw
    env_file:
      - .env
    security_opt:
      - no-new-privileges:true
    networks:
      - app_net

  postgres:
    image: postgres:16.2-alpine
    container_name: postgresql
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    security_opt:
      - no-new-privileges:true
    networks:
      - app_net

  redis:
    image: redis:7.2.4-alpine
    container_name: redis
    restart: always
    command: 'redis-server --save 60 1 --loglevel warning --requirepass ${REDIS_PASSWORD}'
    volumes:
      - redis_data:/data
    security_opt:
      - no-new-privileges:true
    networks:
      - app_net

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: unless-stopped
    environment:
      QDRANT__TELEMETRY_DISABLED: true
    volumes:
      - qdrant_data:/qdrant/storage
    security_opt:
      - no-new-privileges:true
    networks:
      - app_net

  tika:
    image: apache/tika:3.0.0.0-BETA2
    container_name: tika
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - app_net

networks:
  app_net:
    name: ragna_network
    driver: bridge
