services:
  ragna_cloud_app:
    image: ragna/cloud-platform-dev
    volumes:
      - /app/node_modules
    ports:
      - 3000:3000
    command: npm run dev

  postgres:
    ports:
      - 5432:5432

  redis:
    ports:
      - 6379:6379
