services:
  app:
    image: ragna/cloud-platform
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.webapp.rule=Host(`app.svenson.ai`)'
      - 'traefik.http.routers.webapp.entrypoints=https'
      - 'traefik.http.services.webapp.loadbalancer.server.port=3000'
      - 'traefik.http.routers.webapp.service=webapp'
      - 'traefik.http.routers.webapp.middlewares=crowdsec-bouncer@file,default@file'
      - 'traefik.http.routers.webapp.tls=true'
      - 'traefik.http.routers.webapp.tls.certresolver=http'
      - 'traefik.docker.network=traefik_net'
    networks:
      traefik_net:
        ipv4_address: 172.18.0.17

  postgres:
    networks:
      - wgnet

networks:
  traefik_net:
    external: true
  wgnet:
    external: true
