services:
  ragna_cloud_app:
    image: ragna/cloud-platform
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.webapp.rule=Host(`platform.ragna-ai.com`)'
      - 'traefik.http.routers.webapp.entrypoints=https'
      - 'traefik.http.services.webapp.loadbalancer.server.port=3000'
      - 'traefik.http.routers.webapp.service=webapp'
      - 'traefik.http.routers.webapp.middlewares=crowdsec-bouncer@file,default@file' #,gzip@file
      - 'traefik.http.routers.webapp.tls=true'
      - 'traefik.http.routers.webapp.tls.certresolver=http'
      - 'traefik.docker.network=traefik_net'
      # Websocket
      - 'traefik.http.routers.ws-webapp.rule=Host(`platform.ragna-ai.com`) && PathPrefix(`/socket.io`)'
      - 'traefik.http.routers.ws-webapp.service=ws-webapp'
      - 'traefik.http.services.ws-webapp.loadbalancer.server.port=3010'
      - 'traefik.http.routers.ws-webapp.middlewares=crowdsec-bouncer@file,websocket@file'
      - 'traefik.http.routers.ws-webapp.tls=true'
    networks:
      traefik_net:
        ipv4_address: 172.18.0.17

  postgres:
    networks:
      - wgnet

networks:
  traefik_net:
    external: true
  wgnet:
    external: true
