import prisma from '~/server/prisma';
import { s3Client } from '~/server/s3client';
import { AssistantService } from '~/server/services/assistant.service';
import { ChatService } from '~/server/services/chat.service';
import { CollectionAbleService } from '~/server/services/collection-able.service';
import { CollectionService } from '~/server/services/collection.service';
import { DocumentItemService } from '~/server/services/document-item.service';
import { DocumentService } from '~/server/services/document.service';
import { ImageGenService } from '~/server/services/image-gen.service';
import { LLMService } from '~/server/services/llm.service';
import { MediaAbleService } from '~/server/services/media-able.service';
import { MediaService } from '~/server/services/media.service';
import { StorageService } from '~/server/services/storage.service';
import { TeamService } from '~/server/services/team.service';
import { UserService } from '~/server/services/user.service';
import { CreatesNewUserAction } from './actions/createsNewUserAction';
import { ProjectService } from './services/project.service';
import { ProviderAuthService } from './services/provider-auth.service';
import { EmbeddingService } from './services/embedding.service';
import qdrant from './qdrant';
import openai from './openai';
import cohere from './cohere';
import { RecordService } from './services/record.service';
import { StripeService } from './services/stripe.service';
import { UsageService } from './services/usage.service';
import { WorkflowExecutionService } from './services/workflow-execution.service';
import { WorkflowStepService } from './services/workflow-step.service';
import { WorkflowService } from './services/workflow.service';

export const config = useRuntimeConfig();
export const llmService = new LLMService(prisma);
export const fluxImageGenerator = new FluxImageGenerator(config.flux.apiKey);
export const imageGenService = new ImageGenService(fluxImageGenerator);
export const userService = new UserService(prisma);
export const teamService = new TeamService(prisma);
export const chatService = new ChatService(prisma);
export const assistantService = new AssistantService(prisma);
export const collectionAbleService = new CollectionAbleService(prisma);
export const collectionService = new CollectionService(prisma);
export const documentService = new DocumentService(prisma);
export const documentItemService = new DocumentItemService(prisma);
export const storageService = new StorageService(s3Client);
export const mediaAbleService = new MediaAbleService(prisma);
export const mediaService = new MediaService(prisma, mediaAbleService, storageService);
export const projectService = new ProjectService(prisma);
export const providerAuthService = new ProviderAuthService(prisma);
export const embeddingService = new EmbeddingService(qdrant, openai, cohere, config.fileReaderServer.url);
export const recordService = new RecordService(prisma, mediaService, embeddingService);
export const usageService = new UsageService(prisma);
export const stripeService = new StripeService();
export const workflowExecService = new WorkflowExecutionService(prisma);
export const workflowStepService = new WorkflowStepService(prisma);
export const workflowService = new WorkflowService(prisma);

export const createNewUserAction = new CreatesNewUserAction(prisma);
